// <auto-generated />
using AngCore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngCore.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190507225353_UpdateTodo")]
    partial class UpdateTodo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("AngCore.API.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new { Id = 1, Completed = false, Description = "Clean my room and Closet.", Name = "Clean my room." },
                        new { Id = 2, Completed = false, Description = "Hang pictures in the office", Name = "Hang the pictures" },
                        new { Id = 3, Completed = false, Description = "Finish coding the todo app.", Name = "Finish the Todo App" }
                    );
                });

            modelBuilder.Entity("AngCore.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new { Id = 1, Name = "Value 1" },
                        new { Id = 2, Name = "Value 2" },
                        new { Id = 3, Name = "Value 3" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
